# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'WebApp-Terraform'
    backendServiceArm: 'Mike-Pay-As-You-Go (220284d2-6a19-4781-87f8-5c564ec4fec9)'
    backendAzureRmResourceGroupName: 'dev2'
    backendAzureRmStorageAccountName: 'storemfwmw3heqnyuk'
    backendAzureRmContainerName: 'testcontainer'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'WebApp-Terraform'
    commandOptions: '-var="location=eastus" -var="RG=Dev2" -var="name=cloudskillsweb"'
    environmentServiceNameAzureRM: 'Mike-Pay-As-You-Go (220284d2-6a19-4781-87f8-5c564ec4fec9)'